# Plotting networks in R 
# An example how to use R and rgexf package to create a .gexf file for network visualization in Gephi

############################################################################################
# Clear workspace 
rm(list = ls())

# working directory

setwd("/Users/Jessica/Documents/Data Vis/Final Project/Congress")

#install.packages("rjson")

library("rjson")

congress.1 <- fromJSON(file="0103.json", unexpected.escape = "error")
congress.2 <- fromJSON(file="0106.json", unexpected.escape = "error")
congress.3 <- fromJSON(file="0110.json", unexpected.escape = "error")
congress.4 <- fromJSON(file="0112.json", unexpected.escape = "error")
congress.5 <- fromJSON(file="0113.json", unexpected.escape = "error")
congress.6 <- fromJSON(file="0117.json", unexpected.escape = "error")
congress.7 <- fromJSON(file="0118.json", unexpected.escape = "error")
congress.8 <- fromJSON(file="0119.json", unexpected.escape = "error")
congress.9 <- fromJSON(file="0120.json", unexpected.escape = "error")
congress.10 <- fromJSON(file="0123.json", unexpected.escape = "error")
congress.11 <- fromJSON(file="0124.json", unexpected.escape = "error")
congress.12 <- fromJSON(file="0125.json", unexpected.escape = "error")
congress.13 <- fromJSON(file="0126.json", unexpected.escape = "error")
congress.14 <- fromJSON(file="0127.json", unexpected.escape = "error")
congress.15 <- fromJSON(file="0130.json", unexpected.escape = "error")
congress.16 <- fromJSON(file="0131.json", unexpected.escape = "error")
congress.17 <- fromJSON(file="0201.json", unexpected.escape = "error")
congress.18 <- fromJSON(file="0202.json", unexpected.escape = "error")
congress.19 <- fromJSON(file="0203.json", unexpected.escape = "error")
congress.20 <- fromJSON(file="0206.json", unexpected.escape = "error")
congress.21 <- fromJSON(file="0207.json", unexpected.escape = "error")
congress.22 <- fromJSON(file="0208.json", unexpected.escape = "error")
congress.23 <- fromJSON(file="0209.json", unexpected.escape = "error")
congress.24 <- fromJSON(file="0210.json", unexpected.escape = "error")
congress.25 <- fromJSON(file="0213.json", unexpected.escape = "error")
congress.26 <- fromJSON(file="0214.json", unexpected.escape = "error")
congress.27 <- fromJSON(file="0215.json", unexpected.escape = "error")
congress.28 <- fromJSON(file="0216.json", unexpected.escape = "error")
congress.29 <- fromJSON(file="0217.json", unexpected.escape = "error")
congress.30 <- fromJSON(file="0221.json", unexpected.escape = "error")
congress.31 <- fromJSON(file="0222.json", unexpected.escape = "error")
congress.32 <- fromJSON(file="0223.json", unexpected.escape = "error")
congress.33 <- fromJSON(file="0224.json", unexpected.escape = "error")
congress.34 <- fromJSON(file="0227.json", unexpected.escape = "error")
congress.35 <- fromJSON(file="0228.json", unexpected.escape = "error")
congress.36 <- fromJSON(file="0229.json", unexpected.escape = "error")
congress.37 <- fromJSON(file="0301.json", unexpected.escape = "error")
congress.38 <- fromJSON(file="0305.json", unexpected.escape = "error")
congress.39 <- fromJSON(file="0306.json", unexpected.escape = "error")
congress.40 <- fromJSON(file="0307.json", unexpected.escape = "error")
congress.41 <- fromJSON(file="0308.json", unexpected.escape = "error")
congress.42 <- fromJSON(file="0309.json", unexpected.escape = "error")
congress.43 <- fromJSON(file="0312.json", unexpected.escape = "error")
congress.44 <- fromJSON(file="0313.json", unexpected.escape = "error")
congress.45 <- fromJSON(file="0314.json", unexpected.escape = "error")
congress.46 <- fromJSON(file="0315.json", unexpected.escape = "error")
congress.47 <- fromJSON(file="0316.json", unexpected.escape = "error")
congress.48 <- fromJSON(file="0319.json", unexpected.escape = "error")
congress.49 <- fromJSON(file="0320.json", unexpected.escape = "error")
congress.50 <- fromJSON(file="0321.json", unexpected.escape = "error")
congress.51 <- fromJSON(file="0322.json", unexpected.escape = "error")
congress.52 <- fromJSON(file="0323.json", unexpected.escape = "error")
congress.53 <- fromJSON(file="0326.json", unexpected.escape = "error")
congress.54 <- fromJSON(file="0327.json", unexpected.escape = "error")
congress.55 <- fromJSON(file="0328.json", unexpected.escape = "error")
congress.56 <- fromJSON(file="0329.json", unexpected.escape = "error")
congress.57 <- fromJSON(file="0330.json", unexpected.escape = "error")
congress.58 <- fromJSON(file="0402.json", unexpected.escape = "error")
congress.59 <- fromJSON(file="0405.json", unexpected.escape = "error")
congress.60 <- fromJSON(file="0409.json", unexpected.escape = "error")
congress.61 <- fromJSON(file="0410.json", unexpected.escape = "error")
congress.62 <- fromJSON(file="0412.json", unexpected.escape = "error")
congress.63 <- fromJSON(file="0416.json", unexpected.escape = "error")
congress.64 <- fromJSON(file="0417.json", unexpected.escape = "error")
congress.65 <- fromJSON(file="0418.json", unexpected.escape = "error")
congress.66 <- fromJSON(file="0419.json", unexpected.escape = "error")
congress.67 <- fromJSON(file="0420.json", unexpected.escape = "error")
congress.68 <- fromJSON(file="0423.json", unexpected.escape = "error")
congress.69 <- fromJSON(file="0424.json", unexpected.escape = "error")
congress.70 <- fromJSON(file="0425.json", unexpected.escape = "error")
congress.71 <- fromJSON(file="0426.json", unexpected.escape = "error")
congress.72 <- fromJSON(file="0427.json", unexpected.escape = "error")
congress.73 <- fromJSON(file="0430.json", unexpected.escape = "error")
congress.74 <- fromJSON(file="0501.json", unexpected.escape = "error")
congress.75 <- fromJSON(file="0502.json", unexpected.escape = "error")
congress.76 <- fromJSON(file="0503.json", unexpected.escape = "error")
congress.77 <- fromJSON(file="0508.json", unexpected.escape = "error")
congress.78 <- fromJSON(file="0509.json", unexpected.escape = "error")
congress.79 <- fromJSON(file="0510.json", unexpected.escape = "error")
congress.80 <- fromJSON(file="0511.json", unexpected.escape = "error")
congress.81 <- fromJSON(file="0514.json", unexpected.escape = "error")
congress.82 <- fromJSON(file="0515.json", unexpected.escape = "error")
congress.83 <- fromJSON(file="0516.json", unexpected.escape = "error")
congress.84 <- fromJSON(file="0517.json", unexpected.escape = "error")
congress.85 <- fromJSON(file="0518.json", unexpected.escape = "error")
congress.86 <- fromJSON(file="0521.json", unexpected.escape = "error")
congress.87 <- fromJSON(file="0522.json", unexpected.escape = "error")
congress.88 <- fromJSON(file="0523.json", unexpected.escape = "error")
congress.89 <- fromJSON(file="0524.json", unexpected.escape = "error")
congress.90 <- fromJSON(file="0525.json", unexpected.escape = "error")
congress.91 <- fromJSON(file="0529.json", unexpected.escape = "error")
congress.92 <- fromJSON(file="0530.json", unexpected.escape = "error")
congress.93 <- fromJSON(file="0531.json", unexpected.escape = "error")
congress.94 <- fromJSON(file="0601.json", unexpected.escape = "error")
congress.95 <- fromJSON(file="0604.json", unexpected.escape = "error")
congress.96 <- fromJSON(file="0605.json", unexpected.escape = "error")
congress.97 <- fromJSON(file="0606.json", unexpected.escape = "error")
congress.98 <- fromJSON(file="0607.json", unexpected.escape = "error")
congress.99 <- fromJSON(file="0608.json", unexpected.escape = "error")
congress.100 <- fromJSON(file="0611.json", unexpected.escape = "error")
congress.101 <- fromJSON(file="0612.json", unexpected.escape = "error")
congress.102 <- fromJSON(file="0613.json", unexpected.escape = "error")
congress.103 <- fromJSON(file="0614.json", unexpected.escape = "error")
congress.bd.1 <- fromJSON(file="vox_Congress Gov_20121231.json", unexpected.escape = "error")
congress.bd.2 <- fromJSON(file="vox_Congress Gov_20121230.json", unexpected.escape = "error")
congress.bd.3 <- fromJSON(file="vox_Congress Gov_20121228.json", unexpected.escape = "error")
congress.bd.4 <- fromJSON(file="vox_Congress Gov_20121227.json", unexpected.escape = "error")
congress.bd.5 <- fromJSON(file="vox_Congress Gov_20121226.json", unexpected.escape = "error")
congress.bd.6 <- fromJSON(file="vox_Congress Gov_20121221.json", unexpected.escape = "error")
congress.bd.7 <- fromJSON(file="vox_Congress Gov_20121220.json", unexpected.escape = "error")
congress.bd.8 <- fromJSON(file="vox_Congress Gov_20121219.json", unexpected.escape = "error")
congress.bd.9 <- fromJSON(file="vox_Congress Gov_20121218.json", unexpected.escape = "error")
congress.bd.10 <- fromJSON(file="vox_Congress Gov_20121217.json", unexpected.escape = "error")
congress.bd.11 <- fromJSON(file="vox_Congress Gov_20121214.json", unexpected.escape = "error")
congress.bd.12 <- fromJSON(file="vox_Congress Gov_20121213.json", unexpected.escape = "error")
congress.bd.13 <- fromJSON(file="vox_Congress Gov_20121212.json", unexpected.escape = "error")
congress.bd.14 <- fromJSON(file="vox_Congress Gov_20121211.json", unexpected.escape = "error")
congress.bd.15 <- fromJSON(file="vox_Congress Gov_20121210.json", unexpected.escape = "error")
congress.bd.16 <- fromJSON(file="vox_Congress Gov_20121207.json", unexpected.escape = "error")
congress.bd.17 <- fromJSON(file="vox_Congress Gov_20121206.json", unexpected.escape = "error")
congress.bd.18 <- fromJSON(file="vox_Congress Gov_20121205.json", unexpected.escape = "error")
congress.bd.19 <- fromJSON(file="vox_Congress Gov_20121204.json", unexpected.escape = "error")
congress.bd.20 <- fromJSON(file="vox_Congress Gov_20121203.json", unexpected.escape = "error")
congress.bd.21 <- fromJSON(file="vox_Congress Gov_20121130.json", unexpected.escape = "error")
congress.bd.22 <- fromJSON(file="vox_Congress Gov_20121129.json", unexpected.escape = "error")
congress.bd.23 <- fromJSON(file="vox_Congress Gov_20121128.json", unexpected.escape = "error")
congress.bd.24 <- fromJSON(file="vox_Congress Gov_20121127.json", unexpected.escape = "error")
congress.bd.25 <- fromJSON(file="vox_Congress Gov_20121126.json", unexpected.escape = "error")
congress.bd.26 <- fromJSON(file="vox_Congress Gov_20121116.json", unexpected.escape = "error")
congress.bd.27 <- fromJSON(file="vox_Congress Gov_20121115.json", unexpected.escape = "error")
congress.bd.28 <- fromJSON(file="vox_Congress Gov_20121114.json", unexpected.escape = "error")
congress.bd.29 <- fromJSON(file="vox_Congress Gov_20121113.json", unexpected.escape = "error")
congress.bd.30 <- fromJSON(file="vox_Congress Gov_20121109.json", unexpected.escape = "error")
congress.bd.31 <- fromJSON(file="vox_Congress Gov_20121106.json", unexpected.escape = "error")
congress.bd.32 <- fromJSON(file="vox_Congress Gov_20121102.json", unexpected.escape = "error")
congress.bd.33 <- fromJSON(file="vox_Congress Gov_20121026.json", unexpected.escape = "error")
congress.bd.34 <- fromJSON(file="vox_Congress Gov_20121023.json", unexpected.escape = "error")
congress.bd.35 <- fromJSON(file="vox_Congress Gov_20121019.json", unexpected.escape = "error")
congress.bd.36 <- fromJSON(file="vox_Congress Gov_20121016.json", unexpected.escape = "error")
congress.bd.37 <- fromJSON(file="vox_Congress Gov_20121012.json", unexpected.escape = "error")
congress.bd.38 <- fromJSON(file="vox_Congress Gov_20121011.json", unexpected.escape = "error")
congress.bd.39 <- fromJSON(file="vox_Congress Gov_20121010.json", unexpected.escape = "error")
congress.bd.40 <- fromJSON(file="vox_Congress Gov_20121009.json", unexpected.escape = "error")
congress.bd.41 <- fromJSON(file="vox_Congress Gov_20121005.json", unexpected.escape = "error")
congress.bd.42 <- fromJSON(file="vox_Congress Gov_20121004.json", unexpected.escape = "error")
congress.bd.43 <- fromJSON(file="vox_Congress Gov_20121003.json", unexpected.escape = "error")
congress.bd.44 <- fromJSON(file="vox_Congress Gov_20121002.json", unexpected.escape = "error")
congress.bd.45 <- fromJSON(file="vox_Congress Gov_20121001.json", unexpected.escape = "error")
congress.bd.46 <- fromJSON(file="vox_Congress Gov_20120928.json", unexpected.escape = "error")
congress.bd.47 <- fromJSON(file="vox_Congress Gov_20120926.json", unexpected.escape = "error")
congress.bd.48 <- fromJSON(file="vox_Congress Gov_20120925.json", unexpected.escape = "error")
congress.bd.49 <- fromJSON(file="vox_Congress Gov_20120924.json", unexpected.escape = "error")
congress.bd.50 <- fromJSON(file="vox_Congress Gov_20120922.json", unexpected.escape = "error")
congress.bd.51 <- fromJSON(file="vox_Congress Gov_20120921.json", unexpected.escape = "error")
congress.bd.52 <- fromJSON(file="vox_Congress Gov_20120920.json", unexpected.escape = "error")
congress.bd.53 <- fromJSON(file="vox_Congress Gov_20120919.json", unexpected.escape = "error")
congress.bd.54 <- fromJSON(file="vox_Congress Gov_20120917.json", unexpected.escape = "error")
congress.bd.55 <- fromJSON(file="vox_Congress Gov_20120914.json", unexpected.escape = "error")
congress.bd.56 <- fromJSON(file="vox_Congress Gov_20120913.json", unexpected.escape = "error")
congress.bd.57 <- fromJSON(file="vox_Congress Gov_20120912.json", unexpected.escape = "error")
congress.bd.58 <- fromJSON(file="vox_Congress Gov_20120911.json", unexpected.escape = "error")
congress.bd.59 <- fromJSON(file="vox_Congress Gov_20120910.json", unexpected.escape = "error")
congress.bd.60 <- fromJSON(file="vox_Congress Gov_20120907.json", unexpected.escape = "error")
congress.bd.61 <- fromJSON(file="vox_Congress Gov_20120905.json", unexpected.escape = "error")
congress.bd.62 <- fromJSON(file="vox_Congress Gov_20120829.json", unexpected.escape = "error")
congress.bd.63 <- fromJSON(file="vox_Congress Gov_20120828.json", unexpected.escape = "error")
congress.bd.64 <- fromJSON(file="vox_Congress Gov_20120824.json", unexpected.escape = "error")
congress.bd.65 <- fromJSON(file="vox_Congress Gov_20120820.json", unexpected.escape = "error")
congress.bd.66 <- fromJSON(file="vox_Congress Gov_20120816.json", unexpected.escape = "error")
congress.bd.67 <- fromJSON(file="vox_Congress Gov_20120815.json", unexpected.escape = "error")
congress.bd.68 <- fromJSON(file="vox_Congress Gov_20120814.json", unexpected.escape = "error")
congress.bd.69 <- fromJSON(file="vox_Congress Gov_20120813.json", unexpected.escape = "error")
congress.bd.70 <- fromJSON(file="vox_Congress Gov_20120810.json", unexpected.escape = "error")
congress.bd.71 <- fromJSON(file="vox_Congress Gov_20120809.json", unexpected.escape = "error")
congress.bd.72 <- fromJSON(file="vox_Congress Gov_20120808.json", unexpected.escape = "error")
congress.bd.73 <- fromJSON(file="vox_Congress Gov_20120807.json", unexpected.escape = "error")
congress.bd.74 <- fromJSON(file="vox_Congress Gov_20120806.json", unexpected.escape = "error")
congress.bd.75 <- fromJSON(file="vox_Congress Gov_20120803.json", unexpected.escape = "error")
congress.bd.76 <- fromJSON(file="vox_Congress Gov_20120802.json", unexpected.escape = "error")
congress.bd.77 <- fromJSON(file="vox_Congress Gov_20120801.json", unexpected.escape = "error")
congress.bd.78 <- fromJSON(file="vox_Congress Gov_20120731.json", unexpected.escape = "error")
congress.bd.79 <- fromJSON(file="vox_Congress Gov_20120730.json", unexpected.escape = "error")
congress.bd.80 <- fromJSON(file="vox_Congress Gov_20120727.json", unexpected.escape = "error")
congress.bd.81 <- fromJSON(file="vox_Congress Gov_20120726.json", unexpected.escape = "error")
congress.bd.82 <- fromJSON(file="vox_Congress Gov_20120725.json", unexpected.escape = "error")
congress.bd.83 <- fromJSON(file="vox_Congress Gov_20120724.json", unexpected.escape = "error")
congress.bd.84 <- fromJSON(file="vox_Congress Gov_20120723.json", unexpected.escape = "error")
congress.bd.85 <- fromJSON(file="vox_Congress Gov_20120720.json", unexpected.escape = "error")
congress.bd.86 <- fromJSON(file="vox_Congress Gov_20120719.json", unexpected.escape = "error")
congress.bd.87 <- fromJSON(file="vox_Congress Gov_20120718.json", unexpected.escape = "error")
congress.bd.88 <- fromJSON(file="vox_Congress Gov_20120717.json", unexpected.escape = "error")
congress.bd.89 <- fromJSON(file="vox_Congress Gov_20120716.json", unexpected.escape = "error")
congress.bd.90 <- fromJSON(file="0713.json", unexpected.escape = "error")
congress.bd.91 <- fromJSON(file="0712.json", unexpected.escape = "error")
congress.bd.92 <- fromJSON(file="0711.json", unexpected.escape = "error")
congress.bd.93 <- fromJSON(file="0710.json", unexpected.escape = "error")
congress.bd.94 <- fromJSON(file="0709.json", unexpected.escape = "error")
congress.bd.95 <- fromJSON(file="0706.json", unexpected.escape = "error")
congress.bd.96 <- fromJSON(file="0705.json", unexpected.escape = "error")
congress.bd.97 <- fromJSON(file="0702.json", unexpected.escape = "error")
congress.bd.98 <- fromJSON(file="0629.json", unexpected.escape = "error")
congress.bd.99 <- fromJSON(file="0628.json", unexpected.escape = "error")
congress.bd.99 <- fromJSON(file="0627.json", unexpected.escape = "error")
congress.bd.100 <- fromJSON(file="0626.json", unexpected.escape = "error")
congress.bd.101 <- fromJSON(file="0625.json", unexpected.escape = "error")
congress.bd.102 <- fromJSON(file="0622.json", unexpected.escape = "error")
congress.bd.103 <- fromJSON(file="0621.json", unexpected.escape = "error")
congress.bd.104 <- fromJSON(file="0620.json", unexpected.escape = "error")
congress.bd.105 <- fromJSON(file="0619.json", unexpected.escape = "error")
congress.bd.106 <- fromJSON(file="0618.json", unexpected.escape = "error")
congress.bd.107 <- fromJSON(file="0616.json", unexpected.escape = "error")
congress.bd.108 <- fromJSON(file="0615.json", unexpected.escape = "error")

# practice

library(RJSONIO)

practice <- lapply(congress.bd.31[[1]],function(x) c(congress.bd.31[[1]]$id,congress.bd.31[[1]]$description,congress.bd.31[[1]]$secondarySource[[1]]$name,congress.bd.31[[1]]$secondarySource[[1]]$party,congress.bd.31[[1]]$secondarySource[[1]]$gender))

practice <- do.call(rbind,practice)

print(practice)

# getting pretty close